version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app
  deploy:
    steps:
      -checkout
      -run:
        name: Deploy to Heroku
        command: |
            git push https://heroku:908d64da-c11f-4507-a05a-a47011a36c52@git.heroku.com/$HEROKU_APP_NAME.git master