version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Running lint
          command: |
            . venv/bin/activate
            flake8 weird_text_api/ weirdtext_lib/ --ignore=E501,W503
      - store_artifacts:
          path: test-reports/
          destination: python_app

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  build:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
